Repository Squad-31-Hackathon/projeto-front-end-squad-31, pull requests merged in 2024-02, with the labels that each got.

#21 Criacao do botao de login, decodificacao do jwt para capturar os dados do usuario, manipulacao dos dados do usuario
  package-lock.json
  package.json
  src/App.jsx
  src/main.jsx
  src/pages/LoginPage/Login.jsx
Labels: documentation

#23 Merge da branch com as rotas de api
  package-lock.json
  package.json
  src/App.jsx
  src/components/ui/Alert/index.jsx
  src/components/ui/Alert/styles.module.scss
  src/components/ui/header/index.jsx
  src/components/ui/header/styles.module.scss
  src/components/ui/input/index.jsx
  src/contexts/auth.jsx
  src/global.scss
  src/main.jsx
  src/pages/LoginPage/Login.jsx
  src/pages/RegisterPage/Register.jsx
  src/pages/RegisterPage/styles.module.scss
Labels: enhancement

#24 Atualização na coleta de informaçoes no usuário e enviar o projeto na pasta projectsPage
  src/components/ui/button/index.jsx
  src/components/ui/header/index.jsx
  src/components/ui/input/index.jsx
  src/components/ui/modalAdd/index.jsx
  src/components/ui/modalAdd/styles.module.scss
  src/components/ui/tag/index.jsx
  src/contexts/auth.jsx
  src/pages/MeusProjetos/index.jsx
Labels: enhancement

#26 :bug: fix: Problema ao mergear a pasta context
  src/contexts/auth.jsx
Labels: bug

#28 Merge com a versao mais estável
  package-lock.json
  package.json
  src/App.jsx
  src/components/ui/Alert/index.jsx
  src/components/ui/Alert/styles.module.scss
  src/components/ui/button/index.jsx
  src/components/ui/header/index.jsx
  src/components/ui/header/styles.module.scss
  src/components/ui/input/index.jsx
  src/components/ui/modalAdd/index.jsx
  src/components/ui/modalAdd/styles.module.scss
  src/components/ui/tag/index.jsx
  src/contexts/auth.jsx
  src/global.scss
  src/main.jsx
  src/pages/LoginPage/Login.jsx
  src/pages/MeusProjetos/index.jsx
  src/pages/RegisterPage/Register.jsx
  src/pages/RegisterPage/styles.module.scss
Labels: enhancement

#29 Versão para deploy
  package-lock.json
  package.json
  public/LOGO-ORANGEPORTFOLIO.png
  public/add.png
  public/semImagem.png
  src/App.jsx
  src/assets/img_login.png
  src/assets/img_register.png
  src/components/ui/Alert/index.jsx
  src/components/ui/Alert/styles.module.scss
  src/components/ui/button/index.jsx
  src/components/ui/button/styles.module.scss
  src/components/ui/card/index.jsx
  src/components/ui/card/styles.module.scss
  src/components/ui/header/index.jsx
  src/components/ui/header/styles.module.scss
  src/components/ui/input/index.jsx
  src/components/ui/input/styles.module.scss
  src/components/ui/modalAdd/index.jsx
  src/components/ui/modalAdd/styles.module.scss
  src/components/ui/tag/index.jsx
  src/components/ui/tag/styles.module.scss
  src/contexts/auth.jsx
  src/global.scss
  src/main.jsx
  src/pages/Descobrir/index.jsx
  src/pages/Descobrir/styles.module.scss
  src/pages/LoginPage/Login.jsx
  src/pages/LoginPage/styles.module.scss
  src/pages/MeusProjetos/index.jsx
  src/pages/MeusProjetos/styles.module.scss
  src/pages/RegisterPage/Register.jsx
  src/pages/RegisterPage/styles.module.scss
  src/pages/SignIn/index.jsx
  src/pages/SignIn/styles.module.scss
  src/pages/SignUp/index.jsx
  src/pages/SignUp/styles.module.scss
  src/routes/app.routes.jsx
  src/routes/auth.routes.jsx
  src/routes/index.jsx
  src/services/api.jsx
Labels: Deploy

#30 Merge and delete
  package-lock.json
  package.json
  src/components/ui/button/index.jsx
  src/components/ui/button/styles.module.scss
  src/components/ui/card/index.jsx
  src/components/ui/card/styles.module.scss
  src/components/ui/cardMP/index.jsx
  src/components/ui/cardMP/styles.module.scss
  src/components/ui/header/index.jsx
  src/components/ui/header/styles.module.scss
  src/components/ui/modalAdd/index.jsx
  src/components/ui/modalAdd/styles.module.scss
  src/pages/Descobrir/index.jsx
  src/pages/Descobrir/styles.module.scss
  src/pages/MeusProjetos/index.jsx
  src/pages/MeusProjetos/styles.module.scss
  src/pages/RegisterPage/Register.jsx
  src/pages/RegisterPage/styles.module.scss
Labels: enhancement

#31 Versao mais estável do projeto
  package-lock.json
  package.json
  src/components/ui/button/index.jsx
  src/components/ui/button/styles.module.scss
  src/components/ui/card/index.jsx
  src/components/ui/card/styles.module.scss
  src/components/ui/cardMP/index.jsx
  src/components/ui/cardMP/styles.module.scss
  src/components/ui/header/index.jsx
  src/components/ui/header/styles.module.scss
  src/components/ui/modalAdd/index.jsx
  src/components/ui/modalAdd/styles.module.scss
  src/pages/Descobrir/index.jsx
  src/pages/Descobrir/styles.module.scss
  src/pages/MeusProjetos/index.jsx
  src/pages/MeusProjetos/styles.module.scss
  src/pages/RegisterPage/Register.jsx
  src/pages/RegisterPage/styles.module.scss
Labels: documentation

#32 Versão para deploy
  package-lock.json
  package.json
  src/components/ui/button/index.jsx
  src/components/ui/button/styles.module.scss
  src/components/ui/card/index.jsx
  src/components/ui/card/styles.module.scss
  src/components/ui/cardMP/index.jsx
  src/components/ui/cardMP/styles.module.scss
  src/components/ui/header/index.jsx
  src/components/ui/header/styles.module.scss
  src/components/ui/modalAdd/index.jsx
  src/components/ui/modalAdd/styles.module.scss
  src/pages/Descobrir/index.jsx
  src/pages/Descobrir/styles.module.scss
  src/pages/MeusProjetos/index.jsx
  src/pages/MeusProjetos/styles.module.scss
  src/pages/RegisterPage/Register.jsx
  src/pages/RegisterPage/styles.module.scss
Labels: enhancement

#33 Api google
  src/components/ui/card/index.jsx
  src/components/ui/cardMP/index.jsx
  src/components/ui/cardMP/styles.module.scss
  src/components/ui/header/index.jsx
  src/components/ui/header/styles.module.scss
  src/components/ui/modalAdd/index.jsx
  src/components/ui/modalAdd/styles.module.scss
  src/contexts/auth.jsx
  src/global.scss
  src/pages/LoginPage/Login.jsx
  src/pages/LoginPage/styles.module.scss
  src/pages/MeusProjetos/index.jsx
Labels: enhancement

#35 Refactor: Erro no login que quebrava o código
  src/pages/LoginPage/Login.jsx
Labels: bug

#36 Api google
  src/components/ui/cardMP/index.jsx
  src/components/ui/input/index.jsx
  src/components/ui/modalAdd/index.jsx
  src/components/ui/modalAdd/styles.module.scss
  src/global.scss
  src/pages/Descobrir/index.jsx
  src/pages/MeusProjetos/index.jsx
Labels: enhancement

#37 Api google
  src/App.jsx
  src/components/ui/card/index.jsx
  src/components/ui/card/styles.module.scss
  src/components/ui/cardMP/index.jsx
  src/components/ui/cardMP/styles.module.scss
  src/components/ui/modalAdd/styles.module.scss
  src/pages/Descobrir/index.jsx
  src/pages/Descobrir/styles.module.scss
Labels: enhancement

#38 Atualização mais estável
  src/App.jsx
  src/components/ui/Alert/index.jsx
  src/components/ui/card/index.jsx
  src/components/ui/card/styles.module.scss
  src/components/ui/cardMP/index.jsx
  src/components/ui/cardMP/styles.module.scss
  src/components/ui/header/index.jsx
  src/components/ui/header/styles.module.scss
  src/components/ui/input/index.jsx
  src/components/ui/modalAdd/index.jsx
  src/components/ui/modalAdd/styles.module.scss
  src/contexts/auth.jsx
  src/global.scss
  src/pages/Descobrir/index.jsx
  src/pages/Descobrir/styles.module.scss
  src/pages/LoginPage/Login.jsx
  src/pages/LoginPage/styles.module.scss
  src/pages/MeusProjetos/index.jsx
  src/pages/RegisterPage/Register.jsx
Labels: enhancement

#39 Versao do código final para deploy
  src/App.jsx
  src/components/ui/Alert/index.jsx
  src/components/ui/card/index.jsx
  src/components/ui/card/styles.module.scss
  src/components/ui/cardMP/index.jsx
  src/components/ui/cardMP/styles.module.scss
  src/components/ui/header/index.jsx
  src/components/ui/header/styles.module.scss
  src/components/ui/input/index.jsx
  src/components/ui/modalAdd/index.jsx
  src/components/ui/modalAdd/styles.module.scss
  src/contexts/auth.jsx
  src/global.scss
  src/pages/Descobrir/index.jsx
  src/pages/Descobrir/styles.module.scss
  src/pages/LoginPage/Login.jsx
  src/pages/LoginPage/styles.module.scss
  src/pages/MeusProjetos/index.jsx
  src/pages/RegisterPage/Register.jsx
Labels: enhancement

#40 erro login
  src/pages/LoginPage/Login.jsx
Labels: bug

#41 tramento no email errado :bug:
  src/components/ui/Alert/index.jsx
  src/pages/RegisterPage/Register.jsx
Labels: bug
